name: Build and Release

on:
  push:
    tags:
      - "v*" # v1.0.0 gibi tag'ler için

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            asset_name: m-map-windows.exe
            asset_content_type: application/vnd.microsoft.portable-executable
          - os: ubuntu-latest
            asset_name: m-map-linux
            asset_content_type: application/x-executable

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller (Windows)
        if: matrix.os == 'windows-latest'
        run: pyinstaller --onefile --name m-map m-map.py

      - name: Build with PyInstaller (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: pyinstaller --onefile --name m-map m-map.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
